export const eltechShopData = {
  categories: [
    {
      id: 1,
      name: "V\u00eatements",
      description: "Cat\u00e9gorie pour tous les types de v\u00eatements.",
      createdAt: "2025-01-15T04:05:18.106366",
      updatedAt: "2025-01-15T04:05:18.106374",
    },
    {
      id: 2,
      name: "Accessoires",
      description: "Cat\u00e9gorie pour les accessoires de mode.",
      createdAt: "2025-01-15T04:05:18.106377",
      updatedAt: "2025-01-15T04:05:18.106378",
    },
  ],
  products: [
    {
      name: "T-shirt Olivia Garden",
      description: "T-shirt de haute qualité, confortable et léger.",
      detail:
        "Idéal pour un usage quotidien, disponible en plusieurs couleurs.",
      image: "t-shirt-bleu.jpeg",
      imageUrl: "t-shirt-bleu.jpeg",
      is_new: true,
      in_stock: true,
      brand: "Olivia Garden",
      color: "Blanc",
      category: {
        id: 1,
        name: "Vêtements",
      },
      quantity: 50,
      price: 29.3,
    },
    {
      name: "Baskets Air Max",
      description: "Baskets confortables et stylées pour le sport ou la ville.",
      detail: "Semelle rembourrée, disponibles en plusieurs tailles.",
      image: "baskets.webp",
      imageUrl: "basket-airmax.jpeg",
      is_new: true,
      in_stock: true,
      brand: "Nike",
      color: "Blanc",
      category: {
        id: 1,
        name: "Vêtements",
      },
      quantity: 25,
      price: 89.99,
    },
    {
      name: "Pantalon de sport",
      description: "Pantalon léger et extensible pour le fitness ou le yoga.",
      detail: "Tissu respirant, disponible en plusieurs tailles.",
      image: "pantalon.jpg",
      imageUrl: "pantalon.jpg",
      is_new: true,
      in_stock: true,
      brand: "Adidas",
      color: "Bleu",
      category: {
        id: 1,
        name: "Vêtements",
      },
      quantity: 20,
      price: 34.99,
    },
    {
      name: "Veste en denim classique",
      description:
        "Veste intemporelle en denim, idéale pour toutes les saisons.",
      detail:
        "Coupe ajustée, poches pratiques, disponible en plusieurs tailles.",
      image: "veste-denim.jpeg",
      imageUrl: "veste-denim.jpg",
      is_new: true,
      in_stock: true,
      brand: "Levi's",
      color: "Bleu",
      category: {
        id: 1,
        name: "Vêtements Hommes",
      },
      quantity: 15,
      price: 59.99,
    },
    {
      name: "Robe d'été légère",
      description: "Robe fluide et légère pour les journées chaudes.",
      detail: "Tissu respirant, motifs floraux, longueur au genou.",
      image: "robe-ete.jpeg",
      imageUrl: "robe-ete.webp",
      is_new: false,
      in_stock: true,
      brand: "Zara",
      color: "Rose",
      category: {
        id: 1,
        name: "Vêtements Femmes",
      },
      quantity: 30,
      price: 39.99,
    },
  ],
  users: [
    {
      id: "user_001",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "hashed_password_001",
      phoneNumber: "123456789",
      address: "123 Rue de Paris, T\u00e9touan",
      isAdmin: false,
      basket: {
        id: "basket_001",
        userId: "user_001",
        items: [
          {
            product: {
              name: "T-shirt Olivia Garden",
              description:
                "T-shirt de haute qualit\u00e9, confortable et l\u00e9ger.",
              detail:
                "Id\u00e9al pour un usage quotidien, disponible en plusieurs couleurs.",
              image: "https://example.com/images/tshirt.jpg",
              is_new: true,
              in_stock: true,
              brand: "Olivia Garden",
              color: "Blanc",
              category: {
                id: 1,
                name: "V\u00eatements",
              },
              quantity: 50,
              price: 29.3,
            },
            quantity: 2,
            totalPrice: 58.6,
          },
        ],
        totalPrice: 58.6,
        createdAt: "2025-01-15T04:05:18.106383",
        updatedAt: "2025-01-15T04:05:18.106385",
      },
    },
  ],
};