export const eltechShopData = {
  categories: [
    {
      id: 1,
      name: "V\u00eatements",
      description: "Cat\u00e9gorie pour tous les types de v\u00eatements.",
      createdAt: "2025-01-15T04:05:18.106366",
      updatedAt: "2025-01-15T04:05:18.106374",
    },
    {
      id: 2,
      name: "Accessoires",
      description: "Cat\u00e9gorie pour les accessoires de mode.",
      createdAt: "2025-01-15T04:05:18.106377",
      updatedAt: "2025-01-15T04:05:18.106378",
    },
  ],
  products: [
  {
    name: "T-shirt Olivia Garden",
    description: "T-shirt de haute qualité, confortable et léger.",
    detail: "Idéal pour un usage quotidien, disponible en plusieurs couleurs.",
    image: "t-shirt-bleu.jpeg",
    imageUrl: "tshirt.webp",
    is_new: true,
    in_stock: true,
    brand: "Olivia Garden",
    color: "Blanc",
    category: {
      id: 1,
      name: "Vêtements",
    },
    quantity: 50,
    price: 29.3,
  },
  {
    name: "Casquette de sport",
    description: "Casquette légère et respirante pour les activités sportives.",
    detail: "Disponible en différentes couleurs, légère et ajustable.",
    image: "casquette.webp",
    imageUrl: "casquette.webp",
    is_new: false,
    in_stock: true,
    brand: "Nike",
    color: "Noir",
    category: {
      id: 2,
      name: "Accessoires",
    },
    quantity: 100,
    price: 19.99,
  },
  {
    name: "Montre connectée FitPro",
    description: "Montre connectée avec suivi d'activité et notifications.",
    detail: "Écran tactile, waterproof, autonomie de 7 jours.",
    image: "montre.webp",
    imageUrl: "montre.webp",
    is_new: true,
    in_stock: true,
    brand: "FitPro",
    color: "Noir",
    category: {
      id: 3,
      name: "Électronique",
    },
    quantity: 30,
    price: 49.99,
  },
  {
    name: "Baskets Air Max",
    description: "Baskets confortables et stylées pour le sport ou la ville.",
    detail: "Semelle rembourrée, disponibles en plusieurs tailles.",
    image: "baskets.webp",
    imageUrl: "baskets.webp",
    is_new: true,
    in_stock: true,
    brand: "Nike",
    color: "Blanc",
    category: {
      id: 1,
      name: "Vêtements",
    },
    quantity: 25,
    price: 89.99,
  },
  {
    name: "Sac à dos Urban",
    description: "Sac à dos pratique pour le travail ou les études.",
    detail: "Compartiment pour ordinateur portable, résistant à l'eau.",
    image: "sac.webp",
    imageUrl: "sac.webp",
    is_new: false,
    in_stock: true,
    brand: "Urban Style",
    color: "Gris",
    category: {
      id: 2,
      name: "Accessoires",
    },
    quantity: 40,
    price: 39.99,
  },
  {
    name: "Lunettes de soleil Ray",
    description: "Lunettes de soleil avec protection UV400.",
    detail: "Légères et résistantes, design moderne.",
    image: "lunettes.webp",
    imageUrl: "lunettes.webp",
    is_new: false,
    in_stock: true,
    brand: "Ray-Ban",
    color: "Noir",
    category: {
      id: 2,
      name: "Accessoires",
    },
    quantity: 70,
    price: 99.99,
  },
  {
    name: "Pantalon de sport",
    description: "Pantalon léger et extensible pour le fitness ou le yoga.",
    detail: "Tissu respirant, disponible en plusieurs tailles.",
    image: "pantalon.webp",
    imageUrl: "pantalon.webp",
    is_new: true,
    in_stock: true,
    brand: "Adidas",
    color: "Bleu",
    category: {
      id: 1,
      name: "Vêtements",
    },
    quantity: 20,
    price: 34.99,
  },
  {
    name: "Écouteurs sans fil",
    description: "Écouteurs Bluetooth avec réduction de bruit active.",
    detail: "Autonomie de 24h, compatibles avec tous les appareils.",
    image: "ecouteurs.webp",
    imageUrl: "ecouteurs.webp",
    is_new: true,
    in_stock: true,
    brand: "Sony",
    color: "Blanc",
    category: {
      id: 3,
      name: "Électronique",
    },
    quantity: 50,
    price: 59.99,
  },
],
  users: [
    {
      id: "user_001",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      password: "hashed_password_001",
      phoneNumber: "123456789",
      address: "123 Rue de Paris, T\u00e9touan",
      isAdmin: false,
      basket: {
        id: "basket_001",
        userId: "user_001",
        items: [
          {
            product: {
              name: "T-shirt Olivia Garden",
              description:
                "T-shirt de haute qualit\u00e9, confortable et l\u00e9ger.",
              detail:
                "Id\u00e9al pour un usage quotidien, disponible en plusieurs couleurs.",
              image: "https://example.com/images/tshirt.jpg",
              is_new: true,
              in_stock: true,
              brand: "Olivia Garden",
              color: "Blanc",
              category: {
                id: 1,
                name: "V\u00eatements",
              },
              quantity: 50,
              price: 29.3,
            },
            quantity: 2,
            totalPrice: 58.6,
          },
        ],
        totalPrice: 58.6,
        createdAt: "2025-01-15T04:05:18.106383",
        updatedAt: "2025-01-15T04:05:18.106385",
      },
    },
  ],
};